---
- name: Deploy txt file with backup on Windows
  hosts: "{{ deployment_hosts }}"
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Check if destination file exists
      ansible.windows.win_stat:
        path: "{{ dest_file }}"
      register: file_status

    - name: Ensure backup directory exists
      ansible.windows.win_file:
        path: "{{ backup_dir }}"
        state: directory
      when: file_status.stat.exists

    - name: Get current datetime from PowerShell
      ansible.windows.win_shell: "(Get-Date -Format 'yyyyMMdd_HHmmss')"
      register: datetime_output

    - name: Set current datetime fact
      ansible.builtin.set_fact:
        current_datetime: "{{ datetime_output.stdout | trim }}"

    - name: Backup existing txt file with timestamp
      ansible.windows.win_copy:
        src: "{{ dest_file }}"
        dest: "{{ backup_dir }}\\sample_{{ current_datetime }}.txt"
        remote_src: yes
      when: file_status.stat.exists
